#!/bin/sh

build(){
  _debroot_compile $BUILD/arch/src/usplash.c $SOURCES/usplash
  _arch_file_or_depend busybox busybox-static
  _arch_file_or_steal  busybox $SOURCES/
  _depend_apt tmux; }

install(){
  _arch_file_or_steal busybox $DESTDIR/bin/
  cp $SOURCES/usplash $DESTDIR/bin/
  # install busybox
  $DESTDIR/bin/busybox --list-full |
  while read item
    do item=$(basename $item)
    [ -z "$item" ] && continue; printf ",\e[33m$item\e[0m" >&2
    ln -f "$DESTDIR/bin/busybox" "$DESTDIR/bin/$item" || exit 1
  done
  # copy terminfo
  cp -r /lib/terminfo $DESTDIR/lib/
  # copy tic, tmux
  _steal_app tmux; }
