#!/bin/sh

netdrivers(){
  aliases="/lib/modules/$(uname -r)/modules.alias"
  for vend_prod in $(lsusb | cut -c 24-32 | sed 's/:/p/;s/^/v/')
  do
    module=$(grep -i $vend_prod $aliases 2>/dev/null|awk '{print $3}')
    test -z "$module" || { printf "loading $module for $vend_prod: "; modprobe $module && echo ok || echo fail; }
  done; }

netplug(){
  for dev in $(net_eth_devs)
  do [ -d /run/net/$dev ] && continue || mkdir -p /run/net/$dev
  { ifplugd -Ifr /bin/ifplug_event -i $dev
  } >>/run/net/$dev/log 2>&1 </dev/null &
  done
  for dev in $(net_wifi_devs)
  do
    [ -d /run/net/$dev ] && continue || mkdir -p /run/net/$dev
    lsmod |grep -I "^aes " ||
    for m in aes crc32 ccm ctr lib80211_crypt_tkip lib80211_crypt_ccmp lib80211_crypt_wep; do modprobe $m; done
  { wpa_supplicant -P /run/net/$dev/wpa.pid -i$dev -c /etc/wpa_supplicant.conf &
    ifplugd -aIfr /bin/ifplug_event -i $dev -m wlan
    sleep 0.2; wpa_cli -P /run/net/$dev/wpacli.pid -B -a /bin/wpa_event -i $dev -p /run/wpa_supplicant &
  } >>/run/net/$dev/log 2>&1 </dev/null &
  done; }
