#!/bin/sh

build(){
  [ -z "$(_arch_file busybox)" ] &&
  _depend_apt busybox busybox-static
  _depend_apt tmux
  _depend_apt tic ncurses-bin; }

install(){
  local busybox=$(_arch_file busybox)
  if [ -n "$busybox" ]
  then cp $busybox $DESTDIR/bin/busybox
  else _steal_app busybox
  fi
  # install busybox
  $DESTDIR/bin/busybox --list-full |
  while read item
    do item=$(basename $item)
    [ -z "$item" ] && continue; printf ",\e[33m$item\e[0m" >&2
    ln -f "$DESTDIR/bin/busybox" "$DESTDIR/bin/$item" || exit 1
  done
  # copy terminfo
  cp -r /lib/terminfo $DESTDIR/lib/
  # copy tic, tmux
  _steal_app tic tmux; }
