#!/bin/sh

deps(){
  _arch_file_or_depend busybox busybox-static
  _arch_file_or_steal  busybox $SOURCES/
  _depend_apt tmux; }

ramfs(){
  local DESTDIR=$RAMFS
  _arch_file_or_steal busybox $DESTDIR/bin/
  # install busybox
  _exec_debroot "busybox --list" | awk \
  -vreq="sh:mount:sysctl:touch:chvt:find:grep:cat" \
  -vdst="$DESTDIR/bin/" \
  -vsrc="$DESTDIR/bin/busybox" '
  BEGIN{ ORS=","; l = split(req,r,":")+1; for(i=1;i<l;i++) require[r[i]]=1 }
  { if ( require[$1] == 1 ) {
      system("ln -f " src " " dst "/" $1)
      printf("\x1b[32m%s\x1b[0m",$1) }
    # else printf("\x1b[31m%s\x1b[0m",$1);
    }' >&2
  mkdir              -p $DESTDIR/lib/terminfo
  cp -r /lib/terminfo/l $DESTDIR/lib/terminfo/
  cp -r /lib/terminfo/x $DESTDIR/lib/terminfo/
  _steal_app tmux bash htop; }
