#!/bin/sh
# gearos linux kernel buildscript

setup_default(){ _git_source linux https://github.com/torvalds/linux; }

deps_default(){ _is_app bc || apt-get install bc build-essential; }

config_default(){
  [ -f $SOURCES/linux/.config ] && return 0
  cp $(_arch_file linux_config) $SOURCES/linux/.config
  _make -C $SOURCES/linux xconfig; }

kernel_default(){
  [ -f $SOURCES/linux/$KERNEL_IMAGE ] && return 0
  _make -C $SOURCES/linux bzImage modules; }

sysroot_default(){
  [ -d $SYSROOT/usr/include ] && return 0
  mkdir -p $SYSROOT
  _make -C $SOURCES/linux headers_install INSTALL_HDR_PATH=$SYSROOT; }

install_default(){
  _make -C $SOURCES/linux modules_install INSTALL_MOD_PATH=$DESTDIR; }

build(){
  _arch_hook config &&
  _arch_hook kernel &&
  _arch_hook sysroot; }

install(){
  mkdir -p $DESTDIR/lib/modules
  cp -r /lib/firmware $DESTDIR/lib/
  _arch_hook install; }

clean(){
  rm -rf $SYSROOT
  rm $SOURCES/linux/$KERNEL_IMAGE; }

_arch_include linux
_arch_hook deps
_arch_hook setup
