#!/bin/sh

build(){ _depend_apt_lib \
  consolekit dialog dbus \
  usb-utils pci-utils apt-utils \
  net-tools wireless-tools openssh-server \
  bzip2 unrar unlzma zip gzip \
  man tmux vim sudo wget curl pv htop ngrep iotop \
  i3-wm suckless-tools dwb xinit \
  xserver-xorg-video-qxl    \
  xserver-xorg-video-vesa   \
  xserver-xorg-video-fbdev  \
  xserver-xorg-video-intel  \
  xserver-xorg-video-nouveau;
  _arch_hook build_xorg; }

install(){
  _steal_app dmenu i3 xinit Xorg pv htop lspci dwb ngrep iotop;
  for l in libudev.so.1 libselinux.so.1 libgcrypt.so.20 libdl.so.2 libpciaccess.so.0 \
   libdrm.so.2 libpixman-1.so.0 libXfont.so.1 libXau.so.6 libxshmfence.so.1          \
   libXdmcp.so.6 libaudit.so.1 librt.so.1 libresolv.so.2 libcap.so.2 libpcre.so.3    \
   libpthread.so.0 libgpg-error.so.0 libfreetype.so.6 libbz2.so.1.0 libfontenc.so.1  \
   libattr.so.1 libpng12.so.0 libz.so.1 libm.so.6 libgcc_s.so.1
  do _steal_lib $l
  done
  cp -R $DEBIAN/etc/X11 $DESTDIR/etc/
  _arch_hook install_xorg; }
