#!/bin/sh
awk '
function addev(a){ if(!uniq[a]){ dev[++dc] = a; uniq[a] = 1 }}
function madev(m,o,i){
  for(i=1;i<dc;i++){
    if(0 < match(dev[i],m)){
      system("modprobe " o " &")
      dev[i] = "void"
      break }}}
BEGIN{
SYS = "cat /sys/bus/*/devices/*/modalias"
while( 0 < (SYS|getline) ){
  if(!index($0," ")){
       if(0<match($0,/pci:/)){ o = o "\\(" substr($0,1,22) "\\)\\|" }
  else if(0<match($0,/usb:/)){ o = o "\\(" substr($0,1,14) "\\)\\|" }
  else { o = o "\\(" $0              "\\)\\|" }
  addev($0) }
} close(SYS)
GREP = sprintf("grep -i \"%s\" /lib/modules/$(uname -r)/modules.alias",substr(o,1,length(o)-2))
while((GREP|getline)>0){
  gsub(/\*/,".*",$2)
  madev($2,$3)
} close(GREP) }'
echo /bin/hotplug_event >/proc/sys/kernel/hotplug