#!/bin/sh
overlay(){
  test -d /run/.overlay && return 1
  export PATH=/bin HOME=/root
  # early mounts
  mount -t tmpfs tmpfs /run 2>/dev/null
  echo /dev/sda /    squashfs defaults 0 0 >  /etc/mtab 
  echo tmpfs    /run tmpfs    defaults 0 0 >> /etc/mtab
  mount -a
  mkdir -p /dev/pts
  mount -t devpts -o gid=5,mode=620 devpts /dev/pts
  ln -sf /proc/self/fd/0 /dev/stdin
  ln -sf /proc/self/fd/1 /dev/stdout
  ln -sf /proc/self/fd/2 /dev/stderr
  # overlay filesystem
  mkdir /run/.work /run/.overlay /run/.mount
  mount -o bind / /boot/rootfs
  mount -t overlay -o lowerdir=/boot/rootfs,upperdir=/run/.overlay,workdir=/run/.work overlay /boot/overlay
  exec switch_root /boot/overlay /etc/rc; }
overlay