#!/bin/sh
respawn(){
  local t=$(date +%s) r=0
  while "$@"
  do if [ $t -eq $(date +%s) ]
  then r=$(( $r + 1 ))
    if [ $r -gt 4 ]
    then reset; clear
      usplash fini
      echo "[usplash] error: respawning too fast"
      echo "[usplash] dropping to /bin/bash"
      exec /bin/bash -l
      echo "[bash] failed, trying /bin/sh"
      exec /bin/sh -l
      echo "[sh] failed, rebooting..."
      reboot -f
    fi
  else r=0; fi; t=$(date +%s); done; }
respawn _usplash menu "GEAR$(cat /etc/version)/$(cat /etc/release)"