#!/bin/sh
PKGDETAILS_C=false

build(){
  if $PKGDETAILS_C
  then
    _depend_http pkgdetails.c "http://anonscm.debian.org/cgit/d-i/base-installer.git/plain/pkgdetails.c"
    _debroot_compile $SOURCES/pkgdetails.c $SOURCES/pkgdetails
  else
    _depend_http pkgdetails.sh "https://raw.githubusercontent.com/dnschneid/crouton/master/installer/ubuntu/pkgdetails"
  fi
  mkdir -p $SOURCES/debootstrap/scripts
  _depend_http debootstrap/debootstrap     "http://anonscm.debian.org/cgit/d-i/debootstrap.git/plain/debootstrap"
  _depend_http debootstrap/functions       "http://anonscm.debian.org/cgit/d-i/debootstrap.git/plain/functions"
  _depend_http debootstrap/scripts/sid     "http://anonscm.debian.org/cgit/d-i/debootstrap.git/plain/scripts/sid"
  ln -sf sid $SOURCES/debootstrap/scripts/testing
  ln -sf sid $SOURCES/debootstrap/scripts/stable
  _depend_apt kexec kexec-tools
  _depend_apt openssl
  _depend_apt ar binutils
  _depend_apt debootstrap; }

install(){
  for f in dpkg-deb sed ar tar; do rm -f $DESTDIR/bin/$f;done
  _steal_app openssl mkfs.ext4 fsck.ext2 fsck.ext4 sed tar ar dpkg-deb kexec

  __patch(){ cat $1 | sed '
    s|/usr/share/debootstrap|/lib/debootstrap|g
    s|chmod +x|chmod a+x|g
  ' > $2; }
  mkdir -p                                  $DESTDIR/lib/debootstrap/scripts
  __patch  $SOURCES/debootstrap/debootstrap $DESTDIR/bin/debootstrap
  __patch  $SOURCES/debootstrap/functions   $DESTDIR/lib/debootstrap/functions
  for s in $(ls $SOURCES/debootstrap/scripts/*)
    do __patch $s $DESTDIR/lib/debootstrap/scripts/$(basename $s)
  done
  cp $DEBIAN/usr/share/debootstrap/devices.tar.gz $DESTDIR/lib/debootstrap

  if $PKGDETAILS_C
  then
    cp $SOURCES/pkgdetails $DESTDIR/lib/debootstrap/
  else
    cat $SOURCES/pkgdetails.sh |
    sed 's|sh -e|sh|g'         |
    sed 's|mawk|awk|g'         \
    >$DESTDIR/lib/debootstrap/pkgdetails
  fi; chmod a+x $DESTDIR/lib/debootstrap/pkgdetails
  chmod a+x $DESTDIR/bin/debootstrap; }
