#!/bin/sh

setup_armpi2(){
  _git_source linux       https://github.com/raspberrypi/linux
  _git_source linux-tools https://github.com/raspberrypi/tools
  _git_source firmware    https://github.com/raspberrypi/firmware; }

kernel_armpi2(){
  [ -f $SOURCES/linux/$KERNEL_IMAGE ] && return 0
  _make -C $SOURCES/linux zImage modules dtbs 2>&1 |
  _dots "[\e[31mlinux\e[0m]" 25; }

sysroot_armpi2(){
  [ -d $SYSROOT/usr/include ] && return 1
  local r=$(realpath $(arm-linux-gnueabihf-gcc -print-sysroot))
  mkdir -p $SYSROOT/usr
  cp -vr $r/* $SYSROOT/ 2>&1 |
  _dots 'install-sysroot' 2
  _make -C $SOURCES/linux INSTALL_HDR_PATH=$SYSROOT/usr headers_install 2>&1 |
  _dots "[\e[31mlinux\e[0m]" 25; }

install_armpi2(){
  local DEST=$SOURCES/bootfs FW=$SOURCES/firmware
  _make -C $SOURCES/linux INSTALL_MOD_PATH=$DESTDIR modules_install 2>&1 |
  _dots "[\e[31mlinux-modules\e[0m]" 25
  ( cd $SOURCES/linux
    rm -rf $DEST; mkdir -p $DEST/overlays
    cp -r $FW/boot/* arch/arm/boot/dts/*.dtb $DEST/
    cp arch/arm/boot/dts/overlays/*.dtb* arch/arm/boot/dts/overlays/README $DEST/overlays/
    scripts/mkknlimg $KERNEL_IMAGE $DEST/$KERNEL.img
  ); }
