#!/bin/sh

gear0xSPLASH(){                                                  usplash -l"$(echo\
 "%c                              ████████████████                              "'
'"%c                       ███████                ███████                       "'
'"%c                   ████                              ████                   "'
'"%c                ███        ▄██▄  ▄██▄  ▄██▄  ▄██▄        ███                "'
'"%c             ██████        █     █     █  █  █ ▄▀        ██████             "'
'"%c           █████████       █ ▀█  █▀▀   █ ▀█  █▀▄        █████████           "'
'"%c         █████████████     ▀██▀  ▀▄▄▄  █  █  █  █     ▓████████████         "'
'"%c        ███████████████                              ███████████████        "'
'"%c      ██████████████████▓                          ▓██████████████████      "'
'"%c     █████████████████████                        █████████████████████     "'
'"%c    ████████████████████████                    ████████████████████████    "'
'"%c   ███████████████████████████                ███████████████████████████   "'
'"%c   ██████████████████████████   ░▒▓██████▓▒░   ██████████████████████████   "'
'"%c  █████████████████████████   ████████████████   █████████████████████████  "'
'"%c  ████████████████████████  ████████████████████  ████████████████████████  "'
'"%c ████████████████████████  ██████████████████████  ████████████████████████ "'
'"%c ███████████████████████  ████████████████████████  ███████████████████████ "'
'"%c ███████████████████████  ████████████████████████  ███████████████████████ "'
'"%c █                        ████████████████████████                        █ "'
'"%c █                         ██████████████████████                         █ "'
'"%c  █                         ████████████████████                         █  "'
'"%c  █                          ██████████████████                          █  "'
'"%c   █                          ████████████████                          █   "'
'"%c   █                              ▓▓████▓▓                              █   "'
'"%c    █                      ████▓▒          ▒▓█████                     █    "'
'"%c     █                    █████████████████████████                   █     "'
'"%c      ██                ▓███████████████████████████▓               ██      "'
'"%c        █              ███████████████████████████████             █        "'
'"%c         ██          ▓█████████████████████████████████▓         ██         "'
'"%c           ██       █████████████████████████████████████      ██           "'
'"%c             ███  ▓███████████████████████████████████████▓ ███             "'
'"%c                ████████████████████████████████████████████                "'
'"%c                   ██████████████████████████████████████                   "'
'"%c                       ██████████████████████████████                       "'
'"%c                              ████████████████                              " | tac)"; };

gear0xINIT(){ local B=/bin/busybox; exec 2>&1
  export LC_ALL=C LANG=C LC_CTYPE=UTF-8
  export TERM=linux PATH=/usr/bin:/sbin:/bin HOME=/root LD_LIBRARY_PATH=/lib TMP=/run TMPDIR=/run
  $B touch /test 2>/dev/null && $B rm /test || $B mount -o remount,rw /  # remount root if necessary
  $B --install -s /bin
  # init overlay
  . /lib/u/overlay; overlay_init
  # exec /bin/taskd daemon /etc/rc.d
  export USPLASH_TTY=$($B tty) USPLASH_SOCK=/run/usplash
  local header="$(printf "\e[1;44;33m gear$(cat /etc/version)/$(cat /etc/release) [ram]")"
  local footer="$(printf "\e[1;44;34m gear$(cat /etc/version) a minimal hackable OS")"
  mount -t devtmpfs null /dev
  mount -t proc     proc /proc
  exec usplash \
    -mS/run/block/ramfs/overlay \
    -a 'INIT_MODULE=gear0xSTART . /etc/rc'\
    -H "$header" -F "$footer"; }

gear0xSTART(){ gear0xSPLASH
  . /lib/u/overlay; overlay_basemounts
  # verbosity
  sysctl -w kernel.printk="3 4 1 3" >/dev/null 2>&1
  ln    -sf /proc/mounts /etc/mtab
  stty  -F $USPLASH_TTY speed 115200   >/dev/null 2>&1
  ln -sf $1/run $1/tmp # i hate /tmp but it's still hardcoded in some debian packages
  # colors
  local clr=$(printf '\x1b[0m')
  local red=$(printf '\x1b[1;41;30m')
  local grn=$(printf '\x1b[1;42;30m')
  local yel=$(printf '\x1b[1;43;30m')
  # load kmods
  local mod; for mod in virtio_input ext4 usb_storage squashfs overlay xts aes ctr cbc sha256 \
    dm_crypt crc32 ccm lib80211_crypt_tkip lib80211_crypt_ccmp lib80211_crypt_wep \
    usbhid evdev xhci_hcd sdhci sdhci_acpi hid_multitouch i2c_hid \
    mmc_block fat vfat isofs md_mod thermal sd_mod sg efivars
  do modprobe $mod >/dev/null 2>&1
  done

  set_hostname
  hotplug

  modprobe virtio_gpu
  ( while sleep 1; do usplash -w zzz_clock -t "$(printf "\e[43;30m %s \e[0m" "$(date)")"; done; ) & # magic clock

  usplash -i aboot         -t " $yel booting $clr [ enter: rescue console ] "  -a "INIT_MODULE=gear0xUSPLASH_TO_RESCUE . /etc/rc"
  usplash -i aboot:bash    -t " $grn bash    $clr [ plain ] "                  -a "openvt -sc 2 /bin/bash"
  usplash -i aboot:tmux    -t " $grn bash    $clr [ tmux ] "                   -a "openvt -sc 2 /bin/tmux"
  usplash -i acrypto       -t " $grn crypto  $clr [ boot ] "                   -a "openvt -sc 3 /bin/cryptomount"
  usplash -i ainstall      -t " $grn install $clr [ debootstrap ] "            -a "openvt -sc 3 /bin/install-gear"
  usplash -i zreboot       -t " $red reboot  $clr "                            -a "reboot -f"
  usplash -i zreboot:halt  -t " $red halt    $clr "                            -a "halt -f"

  usplash -l "start $yel dropbear $clr"
  gear0xSSH

  usplash -l "start $yel rc.d $clr"
  for lib in $(ls /etc/rc.d|sort) # run rc-scripts
  do
    usplash -l "start $yel rc.d/$lib $clr"
    run_rc $lib
  done

  usplash -d aboot:tmux
  usplash -i aboot -t " $grn bash    $clr [ tmux ] "                   -a "openvt -sc 2 /bin/tmux"

  usplash -l "gear$(cat /etc/version)/$(cat /etc/release) $grn ready $clr"

  read forever
  usplash -i aboot:bash    -t " $grn bash    $clr [ plain ] "                  -a "openvt -sc 2 /bin/bash"
  if [ $$ -eq 1 ]    # if we are still the init process, it's our responsibility
  then gear0xRESCUE; fi;
} # to spawn a shell. else the kernel would panic. (stupid :D)

gear0xRESCUE(){
  export OS_MODE=rescue
  reset; clear;
  setsid cttyhack sh -l
  echo s > /proc/sysrq-trigger
  echo u > /proc/sysrq-trigger
  echo b > /proc/sysrq-trigger; }

gear0xUSPLASH_TO_RESCUE(){
  usplash -q"
    INIT_MODULE=gear0xRESCUE . /etc/rc
  " || setsid cttyhack sh -l; }

gear0xSSH(){ { local p=/run/net/dropbear
  usplash -i ssh -t " starting ssh debug console " -a 'killall -9 dropbearkey dropbear'
  local pw=$(head -c 16 /dev/urandom|busybox od -x|awk '{print $2$3$4$5$6;}' | head -n1)
  echo root:$pw | chpasswd
  usplash -i ssh:info -t " login: root/$pw" -a 'echo change root pw'
  mkdir -p $p
  local key=$(
    dropbearkey -t ecdsa -s 521 -f $p/ecdsa_key 2>&1 |
    awk '/ingerprint/{gsub(/:/,"");print $3}')
  /bin/dropbear -a -r $p/ecdsa_key \
    -E -P $p/pid \
    >$p/log 2>&1
  usplash -i ssh -t " ssh: $key " -a ''; } & }

. /lib/u/gear

[ -n "$INIT_MODULE" ] && { $INIT_MODULE >/dev/null 2>&1 & } || gear0xINIT
