#!/bin/sh

deb_arch(){
  local a="$1"
  [ -z "$a" ] && a=$(uname -m)
  [ -z "$a" ] && echo unknown ||
  case  $a in
  mips|mipsel)  echo mipsel;;
  arm|armeb)    echo arm;;
  armel|armv7l) echo armhf;;
  x86_64|amd64) echo amd64;;
  i386|i686)    echo x86;;
  powerpc)      echo ppc;;
  *)            echo $a;;
  esac; }
