#!/bin/sh

net_devs      (){ ifconfig -a   2>/dev/null | grep -o '^[a-z]\+[a-z0-9.:]\+'; }
net_wifi_devs (){ iw dev | awk '/Interface/{print $2}' 2>/dev/null; }
net_eth_devs  (){ ( ifconfig -a 2>/dev/null | grep encap:Ethernet | awk '{print $1}'; net_wifi_devs; ) | sort | uniq -u; }

set_hostname(){
  export HOSTNAME=$(cat /etc/hostname 2>/dev/null || echo gear)
  hostname $HOSTNAME
  echo 127.0.0.1 $HOSTNAME localhost >> /etc/hosts
  mkdir -p /run/net/lo
  ifconfig lo 127.0.0.1;
  _update_net_widget; }

_update_net_widget(){
  usplash -i net -t "net["$(net_devs|tr "\n" ,|head -c -1)"]" -a ':'; }

_net_add_default(){
  echo "$ACTION: $INTERFACE $EARLY"
  usplash -i net:$INTERFACE -t "$INTERFACE [detected]" -a ':'
  _update_net_widget
  [ "$INTERFACE" = lo ]      && return 0
  [ -d /run/net/$INTERFACE ] && return 0 ||
    mkdir -p /run/net/$INTERFACE
  { if iw dev $INTERFACE 2>/dev/null
  then
    lsmod |grep -I "^aes " ||
    for m in aes crc32 ccm ctr lib80211_crypt_tkip lib80211_crypt_ccmp lib80211_crypt_wep; do modprobe $m; done
    wpa_supplicant -P /run/net/$INTERFACE/wpa.pid -i$INTERFACE -c /etc/wpa_supplicant.conf &
    ifplugd -aIfr /bin/ifplug_event -i $INTERFACE -m wlan
    sleep 0.2; wpa_cli -P /run/net/$INTERFACE/wpacli.pid -B -a /bin/wpa_event -i $INTERFACE -p /run/wpa_supplicant &
  else ifplugd -Ifr /bin/ifplug_event -i $INTERFACE
  fi; } >>/run/net/$INTERFACE/log 2>&1 </dev/null & }
