#!/bin/sh
{ [ -f "$RUNDIR/firmware"       ] && return 0
  [ -f "$TARGET/.gear/firmware" ] || return 0
  touch $RUNDIR/firmware
  overlay_queue "$TARGET"
  usplash -i fw -t " fw: $(busybox uname -mr)" -a ":"
  return 1; }
