#!/bin/sh
{ [ -f "$RUNDIR/firmware"       ] && return 0
  [ -f "$TARGET/.gear/firmware" ] || return 0
  touch $RUNDIR/firmware
  usplash -O "$TARGET";
  usplash -i fw -t " fw: $(busybox uname -mr)" -a ":"
  ugear hotplug;
  return 1; }
