#!/bin/sh
{ if [ -f "$TARGET/bin/systemd" ]
  then usplash -i acboot \
    -t " $grn boot $clr [ $(basename $(dirname $TARGET)) (linux/systemd) ] " \
    -a "usplash -q'. /lib/u/gear; uswitchroot $TARGET /bin/systemd'"
  return 1; fi
  if [ -f "$TARGET/lib/systemd/systemd" ]
  then usplash -i acboot \
      -t " $grn boot $clr [ $(basename $(dirname $TARGET)) (linux/systemd) ] " \
      -a "usplash -q'. /lib/u/gear; uswitchroot $TARGET /lib/systemd/systemd'"
    return 1; fi
  return 0; }
